Add support for PHP8
kingscode/php-klanten-vertellen-api pull request #5
Opened 2021-08-25 13:31 UTC by ben221199

This PR adds support for PHP8.

2021-08-25 14:44 UTC, koenhoeijmakers commented
I think this has a better chance of being merged if you'd just change the php requirement to `"php": ">=7.1",` without all the unnecessary reformatting.

Also could you supply a link to the documentation that states that the `$refCode` should be a `string` or `null`?

2021-08-25 16:37 UTC, ben221199 commented
If you look at the documentation (https://ekomi01.atlassian.net/wiki/spaces/KB/pages/3131146248/KV+Kiyoh+Invite+API), the `refCode` also allows non-decimal characters.

2021-08-26 07:40 UTC, ricardovanlaarhoven requested changes
Please don't change the formatting and for example the indentation into tabs instead of spaces.
This also makes the PR hard to read.

Could you revert those changes and only leave your functional changes

2021-08-26 09:47 UTC, ricardovanlaarhoven requested changes

2021-08-26 09:47 UTC, ricardovanlaarhoven commented on src/API/GetReviews.php
> +}
There are still some formatting changes

2021-08-26 09:47 UTC, ricardovanlaarhoven commented on composer.json
> +        "php": ">=7.1",
Wasn't php8 added here before? Are you sure you want to remove this?
The current `>=7.1` seems good for php8 as well, right?

2021-08-26 10:15 UTC, ben221199 commented on composer.json
> +        "php": ">=7.1",
https://github.com/kingscode/php-klanten-vertellen-api/pull/5#issuecomment-905565291

2021-08-26 18:24 UTC, jspekken requested changes

2021-08-26 18:24 UTC, jspekken commented on composer.json
> +        "php": ">=7.1",
This also matches PHP 8.1 or 9 or... that might cause unnecessary problems. `^7.1|^8.0` is stricter and better suited for whatever the future brings in PHP land.

2021-09-20 14:10 UTC, closed without merging

2021-09-20 18:36 UTC, ben221199 commented
🤔